import type { ToolDefinition, ToolHandler } from "./index";
import { getAllocation } from "../workspace-manager";
import { exec } from "../exec";

/** Default excludes mirror the iOS sync tool — keep these in sync. */
const RSYNC_EXCLUDES = [
  // Version control
  ".git", ".hg", ".svn",
  // Package manager dependencies (keep .dart_tool / .gradle local to the
  // container's build dir — they're regenerated on first build).
  "node_modules", ".pnpm-store", "vendor", "target", ".gradle",
  "Pods", ".dart_tool", ".pub-cache", ".bundle", "elm-stuff",
  "bower_components", "jspm_packages",
  // Virtual environments
  ".venv", "venv", "env", "virtualenv", ".virtualenv", ".conda",
  "conda-env", ".pixi",
  // Build artifacts (these are regenerated by the in-container build)
  "dist", "build", "out", ".next", ".nuxt", ".output", ".svelte-kit",
  ".vercel", ".netlify", "storybook-static", "coverage", ".nyc_output",
  // Caches
  ".cache", ".turbo", ".parcel-cache", ".webpack", ".rollup.cache",
  ".eslintcache", ".stylelintcache", ".prettiercache", "__pycache__",
  ".mypy_cache", ".pytest_cache", ".ruff_cache", ".tox", ".nox",
  ".hypothesis", "*.egg-info", ".eggs",
  // Secrets and credentials
  ".npmrc", ".yarnrc", ".yarnrc.yml", "auth.json", ".netrc",
  "credentials.json", "secrets.json", "*.pem", "*.key", "*.p12",
  "*.pfx", ".aws", ".docker/config.json",
  // OS and IDE files
  ".DS_Store", "Thumbs.db", "desktop.ini", ".Spotlight-V100",
  ".Trashes", ".idea", "*.swp", "*.swo", "*~", ".project",
  ".classpath", ".settings", "*.sublime-*",
  // Logs and temp files
  "*.log", "logs", "tmp", "temp", ".temp", ".tmp",
  "npm-debug.log*", "yarn-debug.log*", "yarn-error.log*",
  "pnpm-debug.log*", "lerna-debug.log*",
  // Compiled files
  "*.pyc", "*.pyo", "*.o", "*.obj", "*.so", "*.dylib", "*.dll", "*.class",
  // Large generated files
  "*.js.map", "*.css.map",
];

const androidSyncCode: ToolHandler = async (_params, allocationId) => {
  const alloc = getAllocation(allocationId);
  if (!alloc) throw new Error("Allocation not found");

  if (!alloc.rsyncEndpoint || !alloc.rsyncSecret) {
    return {
      error:
        "rsync not configured for this allocation. The workspace's rsyncd may not have started yet — wait a few seconds and retry.",
    };
  }

  exec(`mkdir -p "${alloc.buildDir}"`);

  const passwordFile = `${alloc.buildDir}/.rsync-password`;
  const escapedSecret = alloc.rsyncSecret.replace(/'/g, "'\\''");

  try {
    const excludeArgs = RSYNC_EXCLUDES.map((e) => `--exclude=${e}`).join(" ");
    // rsync exit 23 = "partial transfer due to file errors"; we treat it as
    // success because it usually means a symlink target was missing, which
    // doesn't affect the build.
    const cmd = [
      `printf '%s' '${escapedSecret}' > "${passwordFile}"`,
      `chmod 600 "${passwordFile}"`,
      `rsync -az --delete ${excludeArgs} --password-file="${passwordFile}" "${alloc.rsyncEndpoint}" "${alloc.buildDir}/" 2>&1; EC=$?; if [ $EC -eq 0 ] || [ $EC -eq 23 ]; then exit 0; else exit $EC; fi`,
    ].join(" && ");

    exec(cmd, { timeout: 180_000 });

    const fileCount = exec(`find "${alloc.buildDir}" -type f | wc -l`).trim();

    return {
      success: true,
      buildDir: alloc.buildDir,
      fileCount: parseInt(fileCount, 10),
    };
  } catch (error) {
    console.error("[android_sync_code] rsync failed:", error);
    return { error: String(error) };
  } finally {
    try {
      exec(`rm -f "${passwordFile}"`);
    } catch {
      /* ignore */
    }
  }
};

export const syncTools: Array<{ definition: ToolDefinition; handler: ToolHandler }> = [
  {
    definition: {
      name: "android_sync_code",
      description:
        "Sync the workspace's source code into the android container's build dir using rsync. No parameters needed — pulls from the workspace's rsyncd over Tailscale. Call this before android_build_flutter.",
      inputSchema: {
        type: "object",
        properties: {},
      },
    },
    handler: androidSyncCode,
  },
];
