import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

export const previewConfigs = sqliteTable(
  "previewConfigs",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    teamId: text("teamId").notNull(),
    createdByUserId: text("createdByUserId"),
    repoFullName: text("repoFullName").notNull(),
    repoProvider: text("repoProvider"),
    repoInstallationId: integer("repoInstallationId"),
    repoDefaultBranch: text("repoDefaultBranch"),
    environmentId: text("environmentId"),
    status: text("status"),
    lastRunAt: integer("lastRunAt"),
    createdAt: integer("createdAt").notNull(),
    updatedAt: integer("updatedAt").notNull(),
  },
  (table) => [
    index("previewConfigs_by_team_repo").on(table.teamId, table.repoFullName),
    index("previewConfigs_by_team").on(table.teamId, table.updatedAt),
    index("previewConfigs_by_team_status").on(table.teamId, table.status, table.updatedAt),
    index("previewConfigs_by_environment").on(table.environmentId),
    index("previewConfigs_by_installation_repo").on(table.repoInstallationId, table.repoFullName),
  ],
);

export const previewRuns = sqliteTable(
  "previewRuns",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    previewConfigId: text("previewConfigId").notNull(),
    teamId: text("teamId").notNull(),
    repoFullName: text("repoFullName").notNull(),
    repoInstallationId: integer("repoInstallationId"),
    prNumber: integer("prNumber").notNull(),
    prUrl: text("prUrl").notNull(),
    prTitle: text("prTitle"),
    prDescription: text("prDescription"),
    headSha: text("headSha").notNull(),
    baseSha: text("baseSha"),
    headRef: text("headRef"),
    headRepoFullName: text("headRepoFullName"),
    headRepoCloneUrl: text("headRepoCloneUrl"),
    taskRunId: text("taskRunId"),
    status: text("status").notNull(),
    supersededBy: text("supersededBy"),
    stateReason: text("stateReason"),
    dispatchedAt: integer("dispatchedAt"),
    startedAt: integer("startedAt"),
    completedAt: integer("completedAt"),
    screenshotSetId: text("screenshotSetId"),
    githubCommentUrl: text("githubCommentUrl"),
    githubCommentId: integer("githubCommentId"),
    createdAt: integer("createdAt").notNull(),
    updatedAt: integer("updatedAt").notNull(),
  },
  (table) => [
    index("previewRuns_by_config_status").on(table.previewConfigId, table.status, table.createdAt),
    index("previewRuns_by_config_head").on(table.previewConfigId, table.headSha),
    index("previewRuns_by_config_pr").on(table.previewConfigId, table.prNumber, table.createdAt),
    index("previewRuns_by_config_pr_head").on(table.previewConfigId, table.prNumber, table.headSha),
    index("previewRuns_by_team_created").on(table.teamId, table.createdAt),
  ],
);
