import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

export const pullRequests = sqliteTable(
  "pullRequests",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    provider: text("provider").notNull().default("github"),
    installationId: integer("installationId").notNull(),
    repositoryId: integer("repositoryId"),
    repoFullName: text("repoFullName").notNull(),
    number: integer("number").notNull(),
    providerPrId: integer("providerPrId"),
    teamId: text("teamId").notNull(),
    title: text("title").notNull(),
    state: text("state").notNull(), // "open" | "closed"
    merged: integer("merged", { mode: "boolean" }),
    draft: integer("draft", { mode: "boolean" }),
    authorLogin: text("authorLogin"),
    authorId: integer("authorId"),
    htmlUrl: text("htmlUrl"),
    baseRef: text("baseRef"),
    headRef: text("headRef"),
    baseSha: text("baseSha"),
    headSha: text("headSha"),
    mergeCommitSha: text("mergeCommitSha"),
    createdAt: integer("createdAt"),
    updatedAt: integer("updatedAt"),
    closedAt: integer("closedAt"),
    mergedAt: integer("mergedAt"),
    commentsCount: integer("commentsCount"),
    reviewCommentsCount: integer("reviewCommentsCount"),
    commitsCount: integer("commitsCount"),
    additions: integer("additions"),
    deletions: integer("deletions"),
    changedFiles: integer("changedFiles"),
  },
  (table) => [
    index("pullRequests_by_team").on(table.teamId, table.updatedAt),
    index("pullRequests_by_team_state").on(table.teamId, table.state, table.updatedAt),
    index("pullRequests_by_team_repo_number").on(table.teamId, table.repoFullName, table.number),
    index("pullRequests_by_installation").on(table.installationId, table.updatedAt),
    index("pullRequests_by_repo").on(table.repoFullName, table.updatedAt),
  ],
);
