import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

export const tasks = sqliteTable(
  "tasks",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    text: text("text").notNull(),
    isCompleted: integer("isCompleted", { mode: "boolean" }).default(false),
    isArchived: integer("isArchived", { mode: "boolean" }),
    pinned: integer("pinned", { mode: "boolean" }),
    isPreview: integer("isPreview", { mode: "boolean" }),
    isLocalWorkspace: integer("isLocalWorkspace", { mode: "boolean" }),
    isCloudWorkspace: integer("isCloudWorkspace", { mode: "boolean" }),
    linkedFromCloudTaskRunId: text("linkedFromCloudTaskRunId"),
    description: text("description"),
    pullRequestTitle: text("pullRequestTitle"),
    pullRequestDescription: text("pullRequestDescription"),
    projectFullName: text("projectFullName"),
    baseBranch: text("baseBranch"),
    worktreePath: text("worktreePath"),
    generatedBranchName: text("generatedBranchName"),
    createdAt: integer("createdAt"),
    updatedAt: integer("updatedAt"),
    lastActivityAt: integer("lastActivityAt"),
    userId: text("userId").notNull(),
    teamId: text("teamId").notNull(),
    environmentId: text("environmentId"),
    crownEvaluationStatus: text("crownEvaluationStatus"),
    crownEvaluationError: text("crownEvaluationError"),
    mergeStatus: text("mergeStatus"),
    images: text("images", { mode: "json" }),
    screenshotStatus: text("screenshotStatus"),
    screenshotRunId: text("screenshotRunId"),
    screenshotRequestId: text("screenshotRequestId"),
    screenshotRequestedAt: integer("screenshotRequestedAt"),
    screenshotCompletedAt: integer("screenshotCompletedAt"),
    screenshotError: text("screenshotError"),
    screenshotStorageId: text("screenshotStorageId"),
    screenshotMimeType: text("screenshotMimeType"),
    screenshotFileName: text("screenshotFileName"),
    screenshotCommitSha: text("screenshotCommitSha"),
    latestScreenshotSetId: text("latestScreenshotSetId"),
  },
  (table) => [
    index("tasks_by_created").on(table.createdAt),
    index("tasks_by_user").on(table.userId, table.createdAt),
    index("tasks_by_team_user").on(table.teamId, table.userId),
    index("tasks_by_team_user_created").on(table.teamId, table.userId, table.createdAt),
    index("tasks_by_pinned").on(table.pinned, table.teamId, table.userId),
    index("tasks_by_team_preview").on(table.teamId, table.isPreview),
    index("tasks_by_linked_cloud_task_run").on(table.linkedFromCloudTaskRunId),
  ],
);

export const taskVersions = sqliteTable(
  "taskVersions",
  {
    id: text("id").primaryKey().$defaultFn(() => crypto.randomUUID()),
    taskId: text("taskId").notNull(),
    version: integer("version").notNull(),
    diff: text("diff").notNull(),
    summary: text("summary").notNull(),
    createdAt: integer("createdAt").notNull(),
    userId: text("userId").notNull(),
    teamId: text("teamId").notNull(),
    files: text("files", { mode: "json" }).notNull(),
  },
  (table) => [
    index("taskVersions_by_task").on(table.taskId, table.version),
    index("taskVersions_by_team_user").on(table.teamId, table.userId),
  ],
);
