// This file is auto-generated by @hey-api/openapi-ts

export type GetApiInstancesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/instances';
};

export type GetApiInstancesResponses = {
    /**
     * List of instances
     */
    200: {
        instances: Array<{
            id: string;
            status: string;
            paused: boolean;
            ports?: {
                exec: number;
                worker: number;
                vscode: number;
                proxy: number;
                vnc: number;
                devtools: number;
                pty: number;
                androidVnc?: number;
            };
            metadata?: {
                [key: string]: string;
            };
            createdAt: number;
        }>;
    };
};

export type GetApiInstancesResponse = GetApiInstancesResponses[keyof GetApiInstancesResponses];

export type PostApiInstancesData = {
    body: {
        image?: string;
        snapshotId?: string;
        displays?: Array<'android'>;
        metadata?: {
            [key: string]: string;
        };
        region?: string;
    };
    path?: never;
    query?: never;
    url: '/api/instances';
};

export type PostApiInstancesErrors = {
    /**
     * Failed to launch instance
     */
    500: unknown;
};

export type PostApiInstancesResponses = {
    /**
     * Instance launched
     */
    200: {
        id: string;
        status: string;
        ports: {
            exec: number;
            worker: number;
            vscode: number;
            proxy: number;
            vnc: number;
            devtools: number;
            pty: number;
            androidVnc?: number;
        };
        host: string;
    };
};

export type PostApiInstancesResponse = PostApiInstancesResponses[keyof PostApiInstancesResponses];

export type DeleteApiInstancesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/instances/{id}';
};

export type DeleteApiInstancesByIdErrors = {
    /**
     * Failed to destroy instance
     */
    500: unknown;
};

export type DeleteApiInstancesByIdResponses = {
    /**
     * Instance destroyed
     */
    200: {
        destroyed: true;
    };
};

export type DeleteApiInstancesByIdResponse = DeleteApiInstancesByIdResponses[keyof DeleteApiInstancesByIdResponses];

export type GetApiInstancesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/instances/{id}';
};

export type GetApiInstancesByIdErrors = {
    /**
     * Instance not found
     */
    404: unknown;
};

export type GetApiInstancesByIdResponses = {
    /**
     * Instance details
     */
    200: {
        id: string;
        status: string;
        paused: boolean;
        ports?: {
            exec: number;
            worker: number;
            vscode: number;
            proxy: number;
            vnc: number;
            devtools: number;
            pty: number;
            androidVnc?: number;
        };
        metadata?: {
            [key: string]: string;
        };
        createdAt: number;
    };
};

export type GetApiInstancesByIdResponse = GetApiInstancesByIdResponses[keyof GetApiInstancesByIdResponses];

export type PostApiInstancesByIdExecData = {
    body: {
        command: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/instances/{id}/exec';
};

export type PostApiInstancesByIdExecErrors = {
    /**
     * Failed to execute command
     */
    500: unknown;
};

export type PostApiInstancesByIdExecResponses = {
    /**
     * Command executed
     */
    200: {
        exitCode: number;
        stdout: string;
        stderr: string;
    };
};

export type PostApiInstancesByIdExecResponse = PostApiInstancesByIdExecResponses[keyof PostApiInstancesByIdExecResponses];

export type PostApiInstancesByIdStopData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/instances/{id}/stop';
};

export type PostApiInstancesByIdStopErrors = {
    /**
     * Failed to stop instance
     */
    500: unknown;
};

export type PostApiInstancesByIdStopResponses = {
    /**
     * Instance stopped
     */
    200: {
        stopped: true;
    };
};

export type PostApiInstancesByIdStopResponse = PostApiInstancesByIdStopResponses[keyof PostApiInstancesByIdStopResponses];

export type PostApiInstancesByIdPauseData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/instances/{id}/pause';
};

export type PostApiInstancesByIdPauseErrors = {
    /**
     * Failed to pause instance
     */
    500: unknown;
};

export type PostApiInstancesByIdPauseResponses = {
    /**
     * Instance paused
     */
    200: {
        paused: true;
    };
};

export type PostApiInstancesByIdPauseResponse = PostApiInstancesByIdPauseResponses[keyof PostApiInstancesByIdPauseResponses];

export type PostApiInstancesByIdResumeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/instances/{id}/resume';
};

export type PostApiInstancesByIdResumeErrors = {
    /**
     * Failed to resume instance
     */
    500: unknown;
};

export type PostApiInstancesByIdResumeResponses = {
    /**
     * Instance resumed
     */
    200: {
        resumed: true;
    };
};

export type PostApiInstancesByIdResumeResponse = PostApiInstancesByIdResumeResponses[keyof PostApiInstancesByIdResumeResponses];

export type PostApiInstancesByIdSnapshotsData = {
    body: {
        name: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/instances/{id}/snapshots';
};

export type PostApiInstancesByIdSnapshotsErrors = {
    /**
     * Failed to create snapshot
     */
    500: unknown;
};

export type PostApiInstancesByIdSnapshotsResponses = {
    /**
     * Snapshot created
     */
    200: {
        snapshotId: string;
        created: true;
    };
};

export type PostApiInstancesByIdSnapshotsResponse = PostApiInstancesByIdSnapshotsResponses[keyof PostApiInstancesByIdSnapshotsResponses];

export type GetApiSnapshotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/snapshots';
};

export type GetApiSnapshotsResponses = {
    /**
     * List of snapshots
     */
    200: {
        snapshots: Array<{
            id: string;
            containerName: string;
            snapshotName: string;
            createdAt: string;
            stateful: boolean;
        }>;
    };
};

export type GetApiSnapshotsResponse = GetApiSnapshotsResponses[keyof GetApiSnapshotsResponses];

export type DeleteApiSnapshotsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/snapshots/{id}';
};

export type DeleteApiSnapshotsByIdErrors = {
    /**
     * Failed to delete snapshot
     */
    500: unknown;
};

export type DeleteApiSnapshotsByIdResponses = {
    /**
     * Snapshot deleted
     */
    200: {
        deleted: true;
    };
};

export type DeleteApiSnapshotsByIdResponse = DeleteApiSnapshotsByIdResponses[keyof DeleteApiSnapshotsByIdResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};