"use node";
import { v } from "convex/values";
import { fetchInstallationAccessToken } from "../_shared/githubApp";
import { internal } from "./_generated/api";
import { internalAction } from "./_generated/server";

export const addPrReaction = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    content: v.literal("eyes"),
  },
  handler: async (
    _ctx,
    { installationId, repoFullName, prNumber, content },
  ) => {
    try {
      const accessToken = await fetchInstallationAccessToken(installationId);
      if (!accessToken) {
        console.error(
          "[github_pr_comments] Failed to get access token for installation",
          { installationId },
        );
        return { ok: false, error: "Failed to get access token" };
      }

      const response = await fetch(
        `https://api.github.com/repos/${repoFullName}/issues/${prNumber}/reactions`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${accessToken}`,
            Accept: "application/vnd.github+json",
            "Content-Type": "application/json",
            "User-Agent": "cmux-github-bot",
          },
          body: JSON.stringify({ content }),
        },
      );

      if (!response.ok) {
        const errorText = await response.text();
        console.error(
          "[github_pr_comments] Failed to add reaction",
          {
            installationId,
            repoFullName,
            prNumber,
            status: response.status,
            error: errorText,
          },
        );
        return {
          ok: false,
          error: `GitHub API error: ${response.status}`,
        };
      }

      const data = await response.json();
      console.log("[github_pr_comments] Successfully added reaction", {
        installationId,
        repoFullName,
        prNumber,
        reactionId: data.id,
      });

      return { ok: true, reactionId: data.id };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error adding reaction",
        {
          installationId,
          repoFullName,
          prNumber,
          error,
        },
      );
      return {
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});

export const postPreviewComment = internalAction({
  args: {
    installationId: v.number(),
    repoFullName: v.string(),
    prNumber: v.number(),
    screenshotSetId: v.id("previewScreenshotSets"),
    previewRunId: v.id("previewRuns"),
  },
  handler: async (ctx, args) => {
    const { installationId, repoFullName, prNumber, screenshotSetId } = args;

    try {
      const accessToken = await fetchInstallationAccessToken(installationId);
      if (!accessToken) {
        console.error(
          "[github_pr_comments] Failed to get access token for preview comment",
          { installationId },
        );
        return { ok: false, error: "Failed to get access token" };
      }

      // Get screenshot set
      const screenshotSet = await ctx.runQuery(
        internal.previewScreenshots.getScreenshotSet,
        { screenshotSetId },
      );

      if (!screenshotSet) {
        console.error("[github_pr_comments] Screenshot set not found", {
          screenshotSetId,
        });
        return { ok: false, error: "Screenshot set not found" };
      }

      // Build comment body
      let commentBody = "## Preview Screenshots\n\n";

      if (screenshotSet.status === "completed" && screenshotSet.images.length > 0) {
        commentBody += `Successfully captured ${screenshotSet.images.length} screenshot(s) for commit \`${screenshotSet.commitSha.slice(0, 7)}\`:\n\n`;

        for (const image of screenshotSet.images) {
          // Get storage URL for the image
          const storageUrl = await ctx.storage.getUrl(image.storageId);
          if (storageUrl) {
            const fileName = image.fileName || "screenshot";
            commentBody += `### ${fileName}\n`;
            commentBody += `![${fileName}](${storageUrl})\n\n`;
          }
        }

        commentBody += `\n---\n_Generated by [cmux](https://cmux.sh) preview system_`;
      } else if (screenshotSet.status === "failed") {
        commentBody += `Failed to capture screenshots: ${screenshotSet.error || "Unknown error"}\n\n`;
        commentBody += `\n---\n_Generated by [cmux](https://cmux.sh) preview system_`;
      } else if (screenshotSet.status === "skipped") {
        commentBody += `Screenshot capture was skipped: ${screenshotSet.error || "No preview configured"}\n\n`;
        commentBody += `\n---\n_Generated by [cmux](https://cmux.sh) preview system_`;
      }

      // Post comment to GitHub
      const response = await fetch(
        `https://api.github.com/repos/${repoFullName}/issues/${prNumber}/comments`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${accessToken}`,
            Accept: "application/vnd.github+json",
            "Content-Type": "application/json",
            "User-Agent": "cmux-github-bot",
          },
          body: JSON.stringify({ body: commentBody }),
        },
      );

      if (!response.ok) {
        const errorText = await response.text();
        console.error("[github_pr_comments] Failed to post preview comment", {
          installationId,
          repoFullName,
          prNumber,
          status: response.status,
          error: errorText,
        });
        return {
          ok: false,
          error: `GitHub API error: ${response.status}`,
        };
      }

      const data = (await response.json()) as { html_url?: string; id?: number };
      console.log("[github_pr_comments] Successfully posted preview comment", {
        installationId,
        repoFullName,
        prNumber,
        commentId: data.id,
        commentUrl: data.html_url,
      });

      // Update preview run with comment URL
      if (data.html_url) {
        await ctx.runMutation(internal.previewRuns.updateStatus, {
          previewRunId: args.previewRunId,
          status: "completed",
          screenshotSetId,
          githubCommentUrl: data.html_url,
        });
      }

      return { ok: true, commentId: data.id, commentUrl: data.html_url };
    } catch (error) {
      console.error(
        "[github_pr_comments] Unexpected error posting preview comment",
        {
          installationId,
          repoFullName,
          prNumber,
          error,
        },
      );
      return {
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  },
});
